export const supabaseUrl = 'https://yavvboamvvqsrcrlpiwx.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdnZib2FtdnZxc3JjcmxwaXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTY2NTgsImV4cCI6MjA3NDk3MjY1OH0.rhPzeTFwpkKdCiJBcUumc9dB_4CLI_3tuKxVITMbR14';
